apiVersion: apps/v1
kind: Deployment
metadata: 
    name: diwali-app
    labels:
        app: diwali-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: diwali-app
    template:
        metadata:
            labels:
                app: diwali-app
        spec:
            containers:
            - name: diwali-app
              image: shashanki12/happy-diwali:latest
              ports:
               - containerPort: 80
              resources:
                limits:
                  cpu: "250m"
                  memory: "200Mi"
              livenessProbe:
                httpGet:
                   path: /
                   port: 80
                initialDelaySeconds: 10
                periodSeconds: 20
              readinessProbe:
                httpGet:
                    path: /
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 10




